### PR TITLE
Fix ssh credential reuse

### PR DESCRIPTION
**Pull request by BoolPurist**
# Problem before this PR

For example If  user wants to add an user to Slurm db and wants manage its directory then he has to enter the ssh credentials twice. This relates to the issue #8 .

## Fix

Put asking for credentials, ssh connection, into one struct. It asks the user for username/password only once and only when the credentials are required the 1 time.

## Once Cell as new dependency 

This crate allows to initialize a field in a lazy way.  Since the field is only set once at the 1. time of access, its mutability is interior. Because of that , the struct SshCredentials can be passed immutably around the app.

### CODE REVIEW

**Comment by dwgnr** [comment]
ok that's a rather big one. Thanks! xD
Definitely makes sense to have the SSH stuff in one place. 
I'm not sure whether we need a separate folder just for `src/ssh/ssh_credential.rs`, but I guess we can do it like this. 

Unfortunately, all my merging today caused some conflicts in this branch. Can you fix those?

**Comment by BoolPurist** [comment]
This folder "src/ssh/" will be populated with other modules related to ssh. I resolve the merge conflicts.

**Comment by BoolPurist** [comment]
@dwgnr merge conflicts are resolved.

**Review by dwgnr — APPROVED** [review]
Tried on my machine and everything still works.

**Pull request merged**
