### PR TITLE
WIP: Docker open ldap, slurm and directory management

### PR DESCRIPTION
**Pull request by BoolPurist**
Releated [issue](https://github.com/th-nuernberg/usermgmt/issues/11).
- [x] working OpenLDAP in docker container
- [x] working Slurmdb in docker container

### CODE REVIEW

**Comment by BoolPurist** [comment]
# Update to slurm docker
I have fiddle around with  https://github.com/giovtorres/slurm-docker-cluster to provide containers as slurm cluter for app. I managed to get the app work to add/list users in the slurmdb. However I need to write an extra docker compose and DockerFile inherting from the Dockerfile and compose file of https://github.com/giovtorres/slurm-docker-cluster . 

## Reasons 
- Need for static IP address on docker container. Our app needs that for the head node address.
- Need to augment Docker image https://github.com/giovtorres/slurm-docker-cluster by OpenSSH daemon and ensure generating ssh host keys, and root user with know password of docker container. Our app connects via ssh !
- Need to ensure spec Account=student exits in slurmdb before adding user.

**Comment by dwgnr** [comment]
Try accessing container via internal hostname (i.e. service name in docker compose).

**Comment by BoolPurist** [comment]
> Try accessing container via internal hostname (i.e. service name in docker compose).

Is not possible by default from the host to a docker container. By default only docker container can address each other via hostname or container name. Hostnames however are not visible to host machine. Would need separated dns service started or adjusted host file on host machines. Static ip address, assigned via docker compose file, works just fine.

**Comment by BoolPurist** [comment]
# Problems with implementing user directory management in the docker container for development

1. setquota does not work because I can not get any mount point mounted with the required mount options 
for disk quota !
2. Creating directory for user does not work because there is no local unix user in a docker container.



## Suggestion to the problem

These are the following workarounds:

- Do not implement user management system in development environment. The PR would be considered done at this point.
- Do implement without setting quota in development environment and 
  create local Unix user over ssh before creating directory, because 
  It could take a while until it works with pulling user from LDAP db in LDAP docker container for the Linux PAM system.

**Review by dwgnr — APPROVED** [review]
lgtm

**Pull request merged**
